- id: doi:10.1038/s41467-020-19637-5
  image: https://i.imgur.com/I47yzfg.png[/img]
  date: 2020-11-19
  description: "For the bulk of my graduate thesis, I focused on the problem of inefficient cardiomyocyte renewal. Cardiomyocytes are terminally differentiated, with a limited capacity for self-renewal. They are, therefore, an important target for regenerative therapy and a model cell type to test the limits of cellular plasticity. My thesis lab had previously shown the Hippo pathway inhibits postnatal proliferative expansion of the myocardium. I led a study in which we created a mouse that conditionally expresses a form of YAP that cannot be inhibited by canonical Hippo signaling1. When I expressed this YAP, called YAP5SA, in adult cardiomyocytes, I observed dramatic chromatin remodeling, re-expression of genes characteristic of developmentally naïve cardiomyocytes, and re-induction of the cell cycle. This discovery is significant because it supports the claim that resident cardiomyocytes can be reprogrammed to multiply. It was also featured in Dev Cell: [Prometheus Unbound in Yap Heart](https://www.sciencedirect.com/science/article/pii/S1534580719301844)"

 #extra-links:
 #   - type: manubot
 #     link: https://greenelab.github.io/knowledge-graph-review/
  tags:
    - allelic series
    - animal models
    - statistical genetics

- id: doi:10.1371/journal.pcbi.1007128
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  #repo: greenelab/meta-review
  extra-links:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
